ADD_INFO: False

WITH_EP: True
SAVE_FOLDER: "envs/env_files"
PRINT_INFO: True
USE_NPZ: True
ADDED_FOLDER_NAME: ""

PURE_MAPS: False
AGENT_LIST: [4, 8, 16, 32, 64, 128, 256]
SIZE_LIST: [20, 40, 80, 160]
DENSITY_LIST: [0.3, 0.65]
WALL_LIST: [1, 10, 20]
TESTS_TO_GENERATE: 20