PLAN_NUM: 1

# RL
FINISH_EPISODE_NUM    : 50000
GAMMA                 : 0.95
LR_Q                  : 2.e-5
ADAPT_LR              : True
ADAPT_COEFF           : 5.e-5 
EXPERIENCE_BUFFER_SIZE: 256 
MAX_EPISODE_LENGTH    : 256 
IL_MAX_EP_LENGTH      : 64 
EPISODE_COUNT         : 0 

OBS_SIZE        : 13
SMALL_OBS_SIZE  : 7
NUM_FUTURE_STEPS: 3
ENVIRONMENT_SIZE_LIST:
- 10
- 60
WALL_COMPONENTS_LIST: 
- 1
- 21
OBSTACLE_DENSITY_LIST: 
- 0
- 0.75
NUM_CHANNELS: {
  0          : 8,
  1          : 9,
  1.2        : 9,
}

A_SIZE                  : 5
NUM_META_AGENTS         : 9 
NUM_IL_META_AGENTS      : 4 
NUM_THREADS             : 8 
NUM_BUFFERS             : 1
SUMMARY_WINDOW          : 10
LOAD_MODEL              : false
RESET_TRAINER           : false
OUTPUT_FOLDER           : "my_outputs"
TRAINING_VERSION        : "DPCT"
MODEL_FOLDER            : "models"
OUTPUT_CONFIG_FILE      : "config.yaml"
GIFS_FOLDER             : "gifs"
TB_DATA_FOLDER          : "tb_data"
OUTPUT_GIFS             : false
GIFS_FREQUENCY_RL       : 128
OUTPUT_IL_GIFS          : false
IL_GIF_PROB             : 0.0001
PRIMING_LENGTH          : 0
MSTAR_CALL_FREQUENCY    : 1
EPISODE_START           : 0
TRAINING                : true
EPISODE_SAMPLES         : 256
GLOBAL_NET_SCOPE        : "global"
